---
repos:
  - repo: local
    hooks:
      - id: megalinter
        name: Megalinter linting
        stages:
          - pre-commit
        language: docker_image
        require_serial: true
        entry: >
          -e DEFAULT_WORKSPACE=/src
          -e CLEAR_REPORT_FOLDER=true
          -e UPDATED_SOURCES_REPORTER=true
          --tmpfs /.cache
          ghcr.io/oxsecurity/megalinter-documentation
