name: Generate timeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "master"
      - "develop"
    paths:
      - timeline/_data/source

jobs:
  generate_timeline:
    name: "Generate the timeline"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the timeline
        run: |
          pip install --upgrade -r .github/scripts/requirements.txt
          python .github/scripts/timeline.py

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add --verbose .
          git commit -m '[skip ci] update the timeline files'
          git push --verbose
        env:
          SOURCE_DIR: ./timeline/_data
          RESULT_DIR: ./timeline/
